### ISSUE TITLE
모달 사이즈 조정시 블랙스크린

### ISSUE THREAD

**Issue by libu1129** [kslhunter/simplysm#34]
Error: Failed to execute 'setItem' on 'Storage': Setting the value of 'segiro.sd-modal.재고선택.size-config' exceeded the quota.
    at SdLocalStorageProvider../node_modules/@simplysm/sd-angular/dist/modules/shared/SdLocalStorageProvider.js.SdLocalStorageProvider.set (http://localhost:50080/client-admin/main.js:96974:22)
    at SdModalControl../node_modules/@simplysm/sd-angular/dist/modules/modal/SdModalControl.js.SdModalControl._saveSizeConfig (http://localhost:50080/client-admin/main.js:94799:28)
    at HTMLHtmlElement.stopDrag (http://localhost:50080/client-admin/main.js:94793:19)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:50080/client-admin/main.js:236144:31)
    at Object.onInvokeTask (http://localhost:50080/client-admin/main.js:63124:33)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:50080/client-admin/main.js:236143:60)
    at Zone../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:50080/client-admin/main.js:235916:47)
    at ZoneTask../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (http://localhost:50080/client-admin/main.js:236219:34)
    at invokeTask (http://localhost:50080/client-admin/main.js:237414:14)
    at HTMLHtmlElement.globalZoneAwareCallback (http://localhost:50080/client-admin/main.js:237440:17

수동으로 모달 사이즈 조정중 위와같은 블랙스크린이 떴습니다. 이미지 첨보가 안되네요

**Comment by kslhunter** [comment]
최신버전에서 수정된 사항입니다만, 아직도 발생하능 거라면 확인이 필요할 듯합니다.
